// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hRr4Ku4vLdDUJqxfYwlFpENOKOAdoBc',
    appId: '1:1077839155998:web:e33c2985d43aee3394af0f',
    messagingSenderId: '1077839155998',
    projectId: 'nexus-tech-2025',
    authDomain: 'nexus-tech-2025.firebaseapp.com',
    storageBucket: 'nexus-tech-2025.firebasestorage.app',
    measurementId: 'G-TYPCWKWNCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKncy2p9iQALF2d1C8QzA4GWXmEL5Ru_E',
    appId: '1:1077839155998:android:055e9c9d9a87b08294af0f',
    messagingSenderId: '1077839155998',
    projectId: 'nexus-tech-2025',
    storageBucket: 'nexus-tech-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB745ZR4siNYjPAh85YuQ0plMNN7p0FdYc',
    appId: '1:1077839155998:ios:0571475fb0c96b5894af0f',
    messagingSenderId: '1077839155998',
    projectId: 'nexus-tech-2025',
    storageBucket: 'nexus-tech-2025.firebasestorage.app',
    iosBundleId: 'br.edu.ifrs.osorio.nexusTech',
  );
}
